In [ ]:
#K-Fold Cross-Validation

from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier
import numpy as np

# Load dataset
data = load_iris()
X = data.data  # fitur
y = data.target  # label

# Inisialisasi model
model = RandomForestClassifier()

# K-Fold Cross-Validation
scores = cross_val_score(model, X, y, cv=5, scoring='accuracy')

# Tampilkan hasil
print(f"Accuracy: {np.mean(scores):.2f} (+/- {np.std(scores):.2f})")


Accuracy: 0.97 (+/- 0.02)


In [7]:
#Confusion Matrix

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix

# Load dataset
data = load_iris()
X = data.data
y = data.target

# Bagi data menjadi data latih dan data uji
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Latih model
model = RandomForestClassifier()
model.fit(X_train, y_train)

# Prediksi
y_pred = model.predict(X_test)

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)


Confusion Matrix:
[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
